title: Valmorbida Andrea
description: My Info
baseurl: /andreavlm
url: https://andreavlm.github.io

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
